#ifndef COMTRADEVIEW_GLOBAL_H
#define COMTRADEVIEW_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COMTRADEVIEW_LIBRARY)
#  define COMTRADEVIEWSHARED_EXPORT Q_DECL_EXPORT
#else
#  define COMTRADEVIEWSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // COMTRADEVIEW_GLOBAL_H
